# Generated by Django 4.1.3 on 2022-11-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Картинка'),
        ),
    ]
