# Generated by Django 4.1.3 on 2022-11-20 22:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(default=1, verbose_name='Полное описание'),
            preserve_default=False,
        ),
    ]
